# charts/nginx-app/values.yaml

# Настройки приложения
replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.25.3-alpine" # Используем alpine, он легче и безопаснее

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Настройки сервиса
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Ресурсы (КРИТИЧНО для Middle-уровня! Datree будет это проверять)
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

# Настройки NodeSelector, Tolerations, Affinity оставляем пустыми для простоты
nodeSelector: {}
tolerations: []
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - nginx-app
        topologyKey: kubernetes.io/hostname

# Добавляем блок autoscaling
autoscaling:
  enabled: false

# Безопасность контейнера
securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 101               # UID пользователя nginx в alpine образе
  allowPrivilegeEscalation: false

