apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nginx-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nginx-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      # 1. Исправляем run-as-non-root: гарантируем некорневой запуск на уровне Пода
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        # 2. Исправляем no-read-only-root-fs: монтируем RAM-диски для логов/кэша Nginx
        volumeMounts:
        - mountPath: /var/cache/nginx
          name: nginx-tmp
        - mountPath: /var/run
          name: nginx-tmp
        - mountPath: /tmp
          name: nginx-tmp
      
      volumes:
      - name: nginx-tmp
        emptyDir: {}
