---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-app-db-secret
  namespace: production
spec:
  encryptedData:
    db-password: AgCXRqwkCEEwziAxcUhUvw1NHyEG6WBAuRqFjzuaiCtN/ANC2bqHaNQuGU/EGwl5FcfnUwydrL0YConb3aiEWNQYxO3K3j1TFczQpifGxgJIlGZ86v7qVEsF3CvrgAmaT8ldATaZ/totZ1v7aSUjY1A4d9NsxAowM2CdTDUNX+uKGTECjExyeZDbwp59T6KsNepWFhddBrhVg7JJuBA9MqkKmDI8pXySu0QEzyzawq38Hieg6LR0JagBf14jIubZzO/50XB8X2Ttl5YGWK2d/AV/fHdPuk/R0NJcnrQHjAOhIpFJH75VVjH6TBAYeU8shKCvK90he62oN/SEfsz/RTZiE0ND8W4PyHsoSPofZIHU008llnchusHtlrkGwQtBuECdcAcO3zTEPUZCOUUSMdVugq6o/z3ROu2piJ+7zyA519An4e0hJJWRaeoldpxSFGQFMlmrqvtQ+XZNNfdLJYRJKHvby0k0IbnoC9NsxXh8dzh28EBgwToLHniQZk186rEPgdYi+6LgiXL2Bq/aJ8/R3JfLanlJqmV/LfG0xlfyl5nk/eQXA/RpbIxq5MGRtAdLoqpabRU9XL2y09MvLD+R9KlGK3dcxNmbRpEbeI+Hhinfdn5wpQNfUzAf4F+U53P5EtEXGySusPV4IVruf43w7I+DAqmlFrK2O3NsnJ2VG5a4vZwI9+MChTtdhud3cydCAV4tu58/N6qVCKY+MAsyJEJiTbY9D5I9
    db-user: AgBwb1x+I6wxx2bpwJxUODWXYdTctPAF3QjLh8W1yUyH51ebF5WUGn9KjMJ3NQYC7iHVgHpxnA111xvoqyU44r/3UVaMdW8H0JBQJrZarRWPRDlrpxY0snqZoP+DBBaFbkkGE1tFBARFllQ3CKu2gWkkkCAtkzNe/Qvmw3prxnztj2GZsz2hX135xc5QO+O2nqPodyx2Gt+tsrLhlpmRcVMyph1NyQHd/zhjKmhYwtyIczvPKUD1uzXyCMxzgTD5A8XREhtqxLBq0vk4Lxa22lKQMkYLobcgVtmXA23znh/zvI/E0MilZDreHWKJ5sQl1pTk4Mc8de0wXPtH6/1fS6LUqarf3AWFoPnMkVr0cwTpB8CZAOnVTVMo/+5K6l7a4mbIZZ4A+tJyM2s2rGp7HLduuHs9Lw/pjnpBqySXKF9iTVz+uicHl9RaZXqkHsRhlnzk5frV0waBnTY+BNX8h7wQkNsjEp2mlt4c3c4v9Ox7hrGdlk48GBiUmaSfFSogv3gy+Sjc1b2whLGCQKpOQxWfaHCQovL8qWYPBGNnePqPwmsf55g8ECirkoxhkQRo/t4BbVthN2ntatBHsLDLoYwuX+Zpr2raaiT1iHcNmzV2bqN1csVeH+btepbC4Ft1sVn74SDd0+uQG9Rm5FhH+SymZ8Kq6/CZzM8qN+lUF/4aWkx+CVzjTs+rAzWDvAfFtHj0mneqvQ==
  template:
    metadata:
      creationTimestamp: null
      name: nginx-app-db-secret
      namespace: production
    type: Opaque
