apiVersion: ENC[AES256_GCM,data:G80=,iv:3ntsJ0ZQq4KygUTpnqf9/iesjy6jptEKxTMbXzj8v9g=,tag:DA3A1lye3tK4G4E+GiXT4Q==,type:str]
kind: ENC[AES256_GCM,data:AkXxvKJI,iv:IoBUMGbJJ9cGO9kCx5B6Mrs9nZ7jo0j3bWk7Bo5nyf8=,tag:6D96tIvwFFk0ZSHL4i1nAQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:F4XJmMWGvFgZR6bA9vStvQTIfg==,iv:fFUhmXadetiHH0Fr3MtheAhoxnKPkREeN5NPpYF6ggw=,tag:Q2zMCa5kNX3jzc4Wa5NHvg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:oqUzD/nLDSl3,iv:yl2F2/cM9K2/9SoEq7BXGfLfxarnckKwuJxPsss08cg=,tag:8vwif5nnE2yGeXblRV4Obw==,type:str]
type: ENC[AES256_GCM,data:8uCUYcd1,iv:XKc7A0OENCLcdH33DGZxzSeV86fxa0ZJ/+zT60hoyoE=,tag:JTz7N91QH9fC8vWpxFgiQA==,type:str]
stringData:
    db-password: ENC[AES256_GCM,data:wqZIYvgGo9Fo8BC9Y8Guls/SRWUS+Dm8Bw==,iv:jDr1VhEJoFvufg59sh46CPBYsXHvRpxAcvIOo88wiGs=,tag:V8rCW8YhSzMw0i/V7gMLOg==,type:str]
    db-user: ENC[AES256_GCM,data:N+7KDD4=,iv:6pRS+xFATPNfS/ou410rATdPBj78FoRyG1PPVAK91DA=,tag:Azxq8pNHvTXQFEi5+j2ayA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15x44jm8tx4jw3a40wvr7yktx8upe6mfl8esdzzrlhdsrwdhxyvhsgmvn8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZ2Vmd3ZJN2Zvdms1OGc0
            amNZMU9IK0psaCt3RE8vVUtVa1ZhTkRaK1E0CkRucVo5dTlaMGhRZHNKaHhiVnNN
            ZGNQU3VzUXZsOS9lakZQWVVLUlZ3OG8KLS0tIFpIUklXSkl3dGJ6WEp5U3E4dGwx
            SHgzb1pWY1hIOVE5S0tYcjhoaVZTTVkKxz6MhwylxKbhadCEXKrpB3zOdQkf8SzV
            eLC2L9Pl8BqBe+7n/RXPLN3OU9d2+EIHs6V49TPuv35Y9xdOlDtNIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T13:33:35Z"
    mac: ENC[AES256_GCM,data:WvlGH6k461dHc+A7xvTuQH2VDk/LeoNfgIcn3SZnVXlacJsR/H0rIPQVMXH+Ie6QpFJGS+3yH2bOOH92MIs0c1R5h4Ja87M4KOsqlwttft/GZbLHts+2HjFlo41ry9Q5xz3rotN5tdR/cL3RiawvaeXO8v0ceaBUwRV3P34Zvjs=,iv:SAh6NBJrBH8DX6rnHwA1adAN9T0brnxT4LHLKCmjn5g=,tag:kc51LTVWrDcvmSc4skamoA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
