apiVersion: ENC[AES256_GCM,data:D1w=,iv:syU7MpxEocK7BdOrp85y3ow5gmXInmZUnv0UqxeR19Y=,tag:d2es3VkNn7w6F3y9+rXhWw==,type:str]
kind: ENC[AES256_GCM,data:t8sFm5CL,iv:Bi2F+K73FYH7zymDgg6/yk06YTouHcFuO2Lw5RsA330=,tag:IhlYAnxXnAn4b87uLGhKQA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B06DOXGsDfLdiCB6E6ECP2ckeg==,iv:tBlThtkBmovq2g0KuEJaQz2hhuTL+aDMnAUw8vn48oI=,tag:+4U85Mbqwvfe0L6H3uLUbg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:YJSjANyrcnbx,iv:4/a5cc0Z7CEgntrV9cOlS++/UCdizuN1akSazsNBNzg=,tag:CJsWWiIRxUiqyzFQayd3qg==,type:str]
type: ENC[AES256_GCM,data:CIvLcD/o,iv:IDMpPYSKjFdcDww/jRxqqTL84+/opc+JPgPjjnpp2DA=,tag:HtkFDt2u7HVwEsx7Fnvn6A==,type:str]
stringData:
    db-password: ENC[AES256_GCM,data:46qrvpcarq74qkoev3N711gWGc+CAcOM9Q==,iv:Ep2iFeO7vVHgT1XQkNnpDUnG07cisZ2MQmcNkVb2zOg=,tag:/tRHn8VVIubRxKW/qD4UnQ==,type:str]
    db-user: ENC[AES256_GCM,data:NrFFvW0=,iv:Z7bEKGkjPSm8/UxorMMi5BXOQDZtcgatLTiViLNjSwA=,tag:LOWvHG76qRacndQN5Q24wQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15x44jm8tx4jw3a40wvr7yktx8upe6mfl8esdzzrlhdsrwdhxyvhsgmvn8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM1Z0eitnMEJlUER1Q2JN
            QlkzYVpkdlpROTBYUHRXeUtrUFg2TUk3K0g0Cm1oaUlKRzBvM21zdkxJNFlkdTZV
            YWw0NlpGQ1ZOcWIzalZ3NjVOUTBXNUEKLS0tIFBtM0ozV0tyRzNSWmlHVnVkSEl6
            T0ZkK0tQcm9SRndSTm10b2ZnVlRvSU0KMbPxPlx8vCGZBkQFkANBjDSWtTQHBMuL
            gRi0QAhPEU64YPUpirXeh3iK+xBQvKsH+9KSUSs/QVbTSyqWHETb5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T19:17:12Z"
    mac: ENC[AES256_GCM,data:ujnrE15ZaDhfIFFwA7fK1y1E0cCVM6R6uD7nPwg+JlYqC1NWpOzk+tGvaMiF4mU3QkOjKIywOhn+upQnhnZx/J+l0164kR+TxcdmgdSFkXVnVfa+FmjSK++Yq1aHc2H2erOXsRjyDIZMHoTgDdjgEq3LyX6MZc+w5uI3au2wsdQ=,iv:qRSxAPivQCFAAkfxCT28URxEFdXg73AeRob5DDsJH70=,tag:nqcStFC4Qk5V6aQ0s/853A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
