name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Show current commit
        run: |
          echo "Checking out commit: $(git rev-parse HEAD)"
          git log -1 --oneline

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.15.0'

      - name: Render Helm templates
        run: helm template my-app charts/nginx-app > rendered-manifests.yaml


      - name: Debug rendered manifests
        run: |
          echo "--- ПЕРВЫЕ 60 СТРОК RENDERED MANIFEST ---"
          head -n 60 rendered-manifests.yaml
          echo "--- КОНЕЦ ПРЕВЬЮ ---"
          echo "Проверяем наличие securityContext:"
          grep -i "securityContext" rendered-manifests.yaml || echo "НЕ НАЙДЕНО!"

      - name: Run Kube-linter
        run: |
          curl -L -o kube-linter https://github.com/stackrox/kube-linter/releases/latest/download/kube-linter-linux
          chmod +x kube-linter
          ./kube-linter lint rendered-manifests.yaml

      - name: Run Trivy config scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'charts/nginx-app/'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
